---
- name: Converge
  hosts: all
  tasks:
    - name: Install Tailscale
      ansible.builtin.include_role:
        name: artis3n.tailscale
      vars:
        tailscale_authkey: "{{ lookup('env', 'TAILSCALE_CI_KEY') }}"

    - name: Configure Tailscale with a new up argument
      ansible.builtin.include_role:
        name: artis3n.tailscale
      vars:
        tailscale_authkey: "{{ lookup('env', 'TAILSCALE_CI_KEY') }}"
        tailscale_up_args: "--advertise-exit-node"

    - name: Attempt to configure Tailscale without previous up argument
      ansible.builtin.include_role:
        name: artis3n.tailscale
      vars:
        tailscale_authkey: "{{ lookup('env', 'TAILSCALE_CI_KEY') }}"

    - name: Reset all previous Tailscale arguments
      ansible.builtin.include_role:
        name: artis3n.tailscale
      vars:
        tailscale_authkey: "{{ lookup('env', 'TAILSCALE_CI_KEY') }}"
        tailscale_up_args: "--reset"
