---
- name: CentOS | Yum Dependencies
  become: true
  yum:
    name: "{{ yum_dependencies }}"
    state: present

- name: CentOS | Add Yum Repo
  become: true
  command: yum-config-manager --add-repo {{ yum_repos[ansible_distribution] }}
  args:
    creates: /etc/yum.repos.d/tailscale.repo

- name: CentOS | Install Tailscale
  become: true
  yum:
    name: "{{ tailscale_package }}"
    disable_gpg_check: true
    state: present
  when: not upgrade_release | bool

- name: CentOS | Install or upgrade Tailscale
  become: true
  yum:
    name: "{{ tailscale_package }}"
    disable_gpg_check: true
    state: present
  when: upgrade_release | bool
