---
- name: Yum Dependencies
  become: yes
  yum:
    name: "{{ yum_dependencies }}"
    state: present

- name: Add Yum Repo
  become: yes
  command: yum-config-manager --add-repo {{ yum_repos[ansible_distribution] }}
  args:
    creates: /etc/yum.repos.d/tailscale.repo

- name: Install Tailscale
  become: yes
  yum:
    name: "{{ tailscale_package }}"
    disable_gpg_check: yes
    state: present
