---
# https://www.jeffgeerling.com/blog/2020/resolving-fedora-dnf-error-no-such-file-or-directory-varlibdnfrpmdblockpid
- name: Wait for systemd to complete initialization. # noqa 303
  command: systemctl is-system-running
  register: systemctl_status
  until: >
    'running' in systemctl_status.stdout or
    'degraded' in systemctl_status.stdout
  retries: 30
  delay: 5
  when: ansible_service_mgr == 'systemd'
  changed_when: false
