---
- name: OpenSUSE | Split Distribution
  ansible.builtin.set_fact:
    tailscale_opensuse_distribution: "{{ ansible_distribution | split(' ') }}"

- name: OpenSUSE | Get Distribution
  ansible.builtin.set_fact:
    tailscale_opensuse_distribution: "{{ tailscale_opensuse_distribution[1] | lower }}"

- name: OpenSUSE | Install Repo Key
  become: true
  ansible.builtin.rpm_key:
    state: present
    key: "{{ tailscale_opensuse_key }}"

- name: OpenSUSE | Install Repo
  become: true
  community.general.zypper_repository:
    repo: "{{ tailscale_opensuse_repository }}"
    state: present

- name: OpenSUSE | Install Tailscale
  become: true
  community.general.zypper:
    name: tailscale
    update_cache: true
    state: '{{ state }}'
