---
- name: OpenSUSE | Remove Repo - Tumbleweed
  become: true
  community.general.zypper_repository:
    repo: "{{ tailscale_opensuse_tumbleweed_repository }}"
    state: absent
  when: ansible_distribution == "openSUSE Tumbleweed"

- name: OpenSUSE | Remove Repo - Leap
  become: true
  community.general.zypper_repository:
    repo: "{{ tailscale_opensuse_leap_repository }}"
    state: absent
  when: ansible_distribution == "openSUSE Leap"

- name: OpenSUSE | Remove Tailscale
  become: true
  community.general.zypper:
    name: tailscale
    update_cache: true
    state: absent
