---
# https://www.jeffgeerling.com/blog/2020/resolving-fedora-dnf-error-no-such-file-or-directory-varlibdnfrpmdblockpid
- name: Fedora | Wait for systemd to complete initialization.  # noqa command-instead-of-module
  ansible.builtin.command: systemctl is-system-running
  register: systemctl_status
  until: >
    'running' in systemctl_status.stdout or
    'degraded' in systemctl_status.stdout
  retries: 30
  delay: 5
  when: ansible_service_mgr == 'systemd'
  changed_when: false

- name: Fedora | Yum Dependencies
  become: true
  ansible.builtin.yum:
    name: "{{ dnf_yum_dependencies }}"
    update_cache: true
    state: present

- name: Fedora | Dnf Dependencies
  become: true
  ansible.builtin.dnf:
    name: "{{ dnf_dependencies }}"
    state: present

- name: Fedora | Add Dnf Repo
  become: true
  ansible.builtin.command: dnf config-manager --add-repo {{ dnf_repos[ansible_distribution] }}
  args:
    creates: /etc/yum.repos.d/tailscale.repo

- name: Fedora | Install Tailscale
  become: true
  ansible.builtin.dnf:
    name: "{{ tailscale_package }}"
    update_cache: true
    state: '{{ state }}'
