---
- name: Fedora | Prepare Systemd
  ansible.builtin.import_tasks: ./systemd.yml

- name: Fedora | Remove Tailscale
  become: true
  ansible.builtin.dnf:
    name: "{{ tailscale_package }}"
    state: absent

# noqa command-instead-of-module
- name: Fedora | Check for Tailscale Repo
  ansible.builtin.shell: |
    set -o pipefail
    dnf repolist | grep tailscale
  register: repolist_tailscale
  changed_when: false
  failed_when:
    - repolist_tailscale.rc != 0
    - repolist_tailscale.rc != 1

- name: Fedora | Remove Dnf Repo
  become: true
  ansible.builtin.command: dnf config-manager --disable tailscale-{{ release_stability | lower }}
  register: dnf_config_output
  changed_when: dnf_config_output.rc != 0
  when: repolist_tailscale.rc != 1
