---
- name: Converge
  hosts: all
  tasks:
    - name: Install Tailscale with custom up argument
      ansible.builtin.include_role:
        name: artis3n.tailscale
      vars:
        tailscale_authkey: "{{ lookup('env', 'TAILSCALE_CI_KEY') }}"
        tailscale_args: "--accept-dns"
