---
- name: Converge
  hosts: instance
  tasks:
    - name: Init tailscale credentials variables
      ansible.builtin.include_tasks: ../default/init_tailscale_vars.yml

    - name: "Include artis3n.tailscale"
      ansible.builtin.include_role:
        name: artis3n.tailscale
      vars:
        state: present
        verbose: true
