---
- name: Prepare
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Create Headscale user
      community.docker.docker_container_exec:
        container: headscale
        command: headscale users create test

    - name: Create preauth key
      community.docker.docker_container_exec:
        container: headscale
        command: headscale preauthkeys create -u test --reusable

    - name: Fetch Headscale container info
      community.docker.docker_container_info:
        name: headscale
      register: headscale_info

    - name: Set hosts override for Headscale
      delegate_to: instance
      ansible.builtin.lineinfile:
        path: /etc/hosts
        line: "{{ headscale_info.container.NetworkSettings.Networks.headscale.IPAddress }}  headscale"
        unsafe_writes: true  # Hosts file in the docker container can't be written to atomically
