---
- name: Converge
  hosts: all
  tasks:
    - name: "Include artis3n.tailscale"
      include_role:
        name: artis3n.tailscale
      vars:
        tailscale_auth_key: "This should be an `ansible-vault` encrypt-string variable"
