---
- name: Converge
  hosts: all
  tasks:
    - name: "Include artis3n.tailscale"
      ansible.builtin.include_role:
        name: artis3n.tailscale
      vars:
        tailscale_auth_key: "{{ lookup('env', 'TAILSCALE_CI_KEY') }}"
        verbose: true
