---
- name: Converge
  hosts: all
  tasks:
    - name: "Include artis3n.tailscale"
      include_role:
        name: artis3n.tailscale
      vars:
        tailscale_auth_key: "{{ lookup('env', 'CI_TAILSCALE_AUTH_KEY') }}"
        verbose: true
