---
dependency:
  name: galaxy
  options:
    requirements-file: requirements.yml
driver:
  name: docker
platforms:
  - name: instance
    image: ${MOLECULE_DISTRO:-geerlingguy/docker-ubuntu2204-ansible:latest}
    command: ${MOLECULE_COMMAND:-/usr/sbin/init}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    docker_networks:
      - name: headscale
    networks:
      - name: bridge
      - name: headscale
    cgroupns_mode: host
    privileged: true
    pre_build_image: true
  - name: headscale
    image: ${HEADSCALE_IMAGE:-headscale/headscale:latest}
    command: headscale serve
    pre_build_image: true
    networks:
      - name: headscale
    volumes:
      - "${MOLECULE_PROJECT_DIRECTORY}/molecule/default/headscale.config.yaml:/etc/headscale/config.yaml"
provisioner:
  name: ansible
verifier:
  name: ansible
scenario:
  name: default
  test_sequence:
    - dependency
    - destroy
    - syntax
    - create
    - prepare
    - converge
    - idempotence
    - verify
    - cleanup
    - destroy
