---
- name: Converge with play vars
  hosts: all
  vars:
    tailscale_auth_key: "{{ lookup('env', 'TAILSCALE_CI_KEY') }}"
    verbose: true
  tasks:
    - name: "Include artis3n.tailscale"
      include_role:
        name: artis3n.tailscale
