---
- name: Verify
  hosts: all
  tasks:
  - name: Get Tailscale status
    become: true
    command: tailscale status
    changed_when: false
    register: tailscale_status
    failed_when:
      - tailscale_status.rc != 0
      - tailscale_status.stdout != "Logged out."

  - name: Assertions
    assert:
      that:
        - tailscale_status.stdout == "Logged out."
