---
- name: Verify
  hosts: all
  tasks:
  - name: Get Tailscale status
    become: true
    ansible.builtin.command: tailscale status
    changed_when: false
    register: tailscale_status
    failed_when:
      - tailscale_status.rc != 0
      - "'Logged out.' not in tailscale_status.stdout"

  - name: Assertions
    ansible.builtin.assert:
      that:
        - "'Logged out.' in tailscale_status.stdout"
