---
- name: Verify
  hosts: all
  tasks:
  - name: Get Tailscale status
    become: yes
    command: tailscale status
    changed_when: false
    register: tailscale_status

  - name: Assertions
    assert:
      that:
        - '"hello.ipn.dev" not in tailscale_status.stdout'
