name: Publish to Ansible Galaxy

on:
  release:
    types:
      - published

  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependency manager
        run: pipx install poetry

      - name: Set up Python 3.x
        id: setup-python
        uses: actions/setup-python@v5
        with:
          python-version-file: pyproject.toml
          cache: 'poetry'

      - name: Install packages
        run: poetry install --no-interaction

      - name: Publish to Ansible Galaxy
        run: |
          poetry run ansible-galaxy role import --token ${{ secrets.ANSIBLE_GALAXY_TOKEN }} artis3n tailscale
